name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Conan
        run: pip install conan

      - name: Configure Conan
        run: |
          conan profile detect --force
          conan config install https://github.com/willtobyte/conan-configs.git --type git

      - name: Create Conan profile
        run: |
          cat > ~/.conan2/profiles/android <<EOF
          include(default)
          [settings]
          os=Android
          os.api_level=34
          arch=armv8
          compiler=clang
          compiler.version=19
          compiler.libcxx=c++_static
          compiler.cppstd=20

          [tool_requires]
          android-ndk/[*]

          [conf]
          user.sdl:android=True
          EOF

      - name: Install dependencies
        run: conan install . --output-folder=build --build=missing --profile=android --settings compiler.cppstd=20 --settings build_type=Release

      - name: Configure & Build
        run: |
          cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel $(nproc) --config Release --verbose

  ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conan
        run: |
          brew install conan
          conan profile detect --force
          conan config install https://github.com/willtobyte/conan-configs.git --type git

      - name: Create Conan profile
        run: |
          cat > ~/.conan2/profiles/ios <<EOF
          include(default)

          [settings]
          os=iOS
          os.version=16.0
          os.sdk=iphoneos
          arch=armv8
          compiler=apple-clang
          compiler.version=17.0
          compiler.libcxx=libc++
          build_type=Release
          EOF

      - name: Install dependencies
        run: conan install . --output-folder=build --build=missing --profile=ios --settings compiler.cppstd=20 --settings build_type=Release

      - name: Configure & Build
        run: |
          cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel $(sysctl -n hw.logicalcpu) --config Release --verbose

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conan
        run: |
          brew install conan
          conan profile detect --force
          conan config install https://github.com/willtobyte/conan-configs.git --type git

      - name: Install dependencies
        run: conan install . --output-folder=build --build=missing --settings compiler.cppstd=20 --settings build_type=Release

      - name: Build
        run: |
          cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel $(sysctl -n hw.logicalcpu) --config Release --verbose

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conan
        run: |
          python3 -m pip install --upgrade pip
          pip install conan
          conan profile detect --force
          conan config install https://github.com/willtobyte/conan-configs.git --type git

      - name: Install dependencies
        run: conan install . --output-folder=build --build=missing --settings compiler.cppstd=20 --settings build_type=Release --conf "tools.system.package_manager:mode=install" --conf "tools.system.package_manager:sudo=True"

      - name: Build
        run: |
          cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel $(nproc) --config Release --verbose

  webassembly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conan
        run: |
          pip install conan
          conan profile detect --force
          conan config install https://github.com/willtobyte/conan-configs.git --type git

      - name: Conan profile
        run: |
          cat > ~/.conan2/profiles/webassembly <<EOF
          include(default)
          [settings]
          arch=wasm
          os=Emscripten
          [tool_requires]
          *: emsdk/3.1.73
          EOF

      - name: Install dependencies
        run: conan install . --output-folder=build --build=missing --profile=webassembly --settings compiler.cppstd=20 --settings build_type=Release

      - name: Build
        run: |
          cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel $(nproc) --config Release --verbose

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conan
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install conan
          conan profile detect --force
          conan config install https://github.com/willtobyte/conan-configs.git --type git

      - name: Install dependencies
        run: conan install . --output-folder=build --build=missing --settings compiler.cppstd=20 --settings build_type=Release

      - name: Build
        run: |
          cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel $Env:NUMBER_OF_PROCESSORS --config Release --verbose
