name: iOS

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 8

jobs:
  build:
    runs-on: macos-latest
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Setup Conan
        run: |
          brew install conan
          conan profile detect --force
          conan config install https://github.com/willtobyte/conan-configs.git --type git

      - name: Configure tools & CMake
        run: |
          cat <<'EOF' >> ~/.conan2/profiles/default
          [replace_tool_requires]
          meson/*: meson/[*]
          pkgconf/*: pkgconf/[*]

          [tool_requires]
          !cmake/*: cmake/[>=3 <4]
          EOF

      - name: Create Conan profile
        run: |
          cat > ~/.conan2/profiles/ios <<EOF
          include(default)

          [settings]
          os=iOS
          os.version=16.3
          os.sdk=iphoneos
          arch=armv8
          compiler=apple-clang
          compiler.version=17.0
          compiler.libcxx=libc++
          build_type=Release

          [conf]
          tools.build:cflags=["-DLUA_USE_IOS=1"]
          EOF

      - name: Install dependencies
        run: conan install . --output-folder=build --build=missing --profile=ios --settings compiler.cppstd=23 --settings build_type=Release

      - name: Build
        run: |
          cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release --verbose
