name: Ubuntu

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GCC 15
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt install -y g++-15
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-15 100
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-15 100

      - name: Setup Conan
        run: |
          python3 -m pip install --upgrade pip
          pip install conan
          conan profile detect --force
          conan config install https://github.com/willtobyte/conan-configs.git --type git

      - name: Configure tools & CMake
        run: |
          cat <<'EOF' >> ~/.conan2/profiles/default
          [replace_tool_requires]
          meson/*: meson/[*]
          pkgconf/*: pkgconf/[*]

          [tool_requires]
          !cmake/*: cmake/[>=3 <4]
          EOF

      - name: Install dependencies
        run: conan install . --output-folder=build --build=missing --settings compiler.cppstd=23 --settings build_type=Release --conf "tools.system.package_manager:mode=install" --conf "tools.system.package_manager:sudo=True"

      - name: Build
        run: |
          cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release --verbose
