name: WebAssembly

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conan
        run: |
          pip install conan
          conan profile detect --force
          conan config install https://github.com/willtobyte/conan-configs.git --type git

      - name: Configure tools & CMake
        run: |
          cat <<'EOF' >> ~/.conan2/profiles/default
          [replace_tool_requires]
          meson/*: meson/[*]
          pkgconf/*: pkgconf/[*]

          [tool_requires]
          !cmake/*: cmake/[>=3 <4]
          EOF

      - name: Conan profile
        run: |
          cat > ~/.conan2/profiles/webassembly <<EOF
          include(default)

          [settings]
          arch=wasm
          os=Emscripten

          [tool_requires]
          *: emsdk/3.1.73
          EOF

      - name: Install dependencies
        run: conan install . --output-folder=build --build=missing --profile=webassembly --settings compiler.cppstd=23 --settings build_type=Release

      - name: Build
        run: |
          cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release --verbose \
            -DCMAKE_C_FLAGS_RELEASE:STRING="-DBOX2D_DISABLE_SIMD -Oz -DNDEBUG -ffunction-sections -fdata-sections -flto -fvisibility=hidden -g0" \
            -DCMAKE_CXX_FLAGS_RELEASE:STRING="-DBOX2D_DISABLE_SIMD -Oz -DNDEBUG -ffunction-sections -fdata-sections -flto -fvisibility=hidden -fvisibility-inlines-hidden -g0" \
            -DCMAKE_EXE_LINKER_FLAGS_RELEASE:STRING="-fuse-ld=lld -flto -Wl,-O2,--gc-sections,-s"
