name: WebAssembly

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conan
        run: |
          pip install conan
          conan profile detect --force
          conan config install https://github.com/willtobyte/conan-configs.git --type git

      - name: Configure tools & CMake
        run: |
          cat <<'EOF' >> ~/.conan2/profiles/default
          [replace_tool_requires]
          meson/*: meson/[*]
          pkgconf/*: pkgconf/[*]

          [tool_requires]
          !cmake/*: cmake/[>=3 <4]
          EOF

      - name: Conan profile
        run: |
          cat > ~/.conan2/profiles/webassembly <<EOF
          include(default)

          [settings]
          arch=wasm
          os=Emscripten

          [tool_requires]
          *: emsdk/3.1.73
          EOF

      - name: Pre-install
        run: |
          conan install . \
            --output-folder=build \
            --profile=webassembly \
            --settings compiler.cppstd=23 \
            --settings build_type=Release \
            --build=missing
        continue-on-error: true

      - name: Patch CMake
        run: |
          find "$ROOT" -type f -name "CMakeLists.txt" -print0 \
            | xargs -0 sed -i -E '
              s/^[[:space:]]*option\s*\(\s*BOX2D_DISABLE_SIMD\s+"[^"]*"\s+OFF\s*\)/option(BOX2D_DISABLE_SIMD "Disable SIMD" ON)/g;
              s/^[[:space:]]*set\s*\(\s*BOX2D_DISABLE_SIMD\s+OFF\s*\)/set(BOX2D_DISABLE_SIMD ON)/g;
              s/if\s*\(\s*BOX2D_DISABLE_SIMD\s+OFF\s*\)/if(BOX2D_DISABLE_SIMD)/g
            '
          while IFS= read -r -d '' f; do
            grep -q '^set(BOX2D_DISABLE_SIMD ON CACHE BOOL "" FORCE)$' "$f" && continue
            sed -i -E '/^[[:space:]]*cmake_minimum_required.*/a set(BOX2D_DISABLE_SIMD ON CACHE BOOL "" FORCE)' "$f"
          done < <(find "$ROOT" -type f -name "CMakeLists.txt" -print0)

      - name: Install dependencies
        run: |
          conan install . \
            --output-folder=build \
            --profile=webassembly \
            --settings compiler.cppstd=23 \
            --settings build_type=Release \
            --build=missing

      - name: Build
        run: |
          cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release --verbose
